# Generated by Django 4.0.2 on 2022-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_alter_produit_image_alter_produit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=510),
        ),
    ]
